name: "GitHub Pull Request Updater Action"
description: "GitHub Action that updates a pull request"
author: "Arthur Vasconcelos"
branding:
  icon: "git-pull-request"
  color: "green"
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
    required: true
  title:
    description: "Title replacement for the PR"
    required: false
    default: ""
  title-prefix:
    description: "Text to be prepended to the PR title"
    required: false
    default: ""
  title-suffix:
    description: "Text to be appended to the PR title"
    required: false
    default: ""
  body:
    description: "Body replacement for the PR"
    required: false
    default: ""
  body-prefix:
    description: "Text to be prepended to the PR body"
    required: false
    default: ""
  body-suffix:
    description: "Text to be appended to the PR body"
    required: false
    default: ""
  body-concat-new-line:
    description: "Flag to indicate whether to add a new line between the body prefix and suffix"
    required: false
    default: "true"
outputs:
  new-title:
    description: "New PR title"
  new-body:
    description: "New PR body"
