name: 'Test'
on:
  pull_request:
    types:
        - opened
        - edited
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      # - uses: kognity/pr-update-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: My new PR Title
          title-prefix: PFX-999
          title-suffix: "[BOT]"
          body: My new PR Body
          body-prefix: Some prefix on the body
          body-suffix: Some suffix on the body
